version: '3'
services:
  app:  
    build: .
    volumes:
      - ".:/var/www/html/app"
    ports:
      - "4200:4200"
    #command: >
    #  bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    #  cd application && ng serve --host 0.0.0.0 --port 4200

