require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/drugs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Drug. As you add validations to Drug, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response", :vcr do
      #Drug.create! valid_attributes
      get drugs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      drug = Drug.create! valid_attributes
      get drug_url(drug)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_drug_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      drug = Drug.create! valid_attributes
      get edit_drug_url(drug)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Drug" do
        expect {
          post drugs_url, params: { drug: valid_attributes }
        }.to change(Drug, :count).by(1)
      end

      it "redirects to the created drug" do
        post drugs_url, params: { drug: valid_attributes }
        expect(response).to redirect_to(drug_url(Drug.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Drug" do
        expect {
          post drugs_url, params: { drug: invalid_attributes }
        }.to change(Drug, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post drugs_url, params: { drug: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested drug" do
        drug = Drug.create! valid_attributes
        patch drug_url(drug), params: { drug: new_attributes }
        drug.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the drug" do
        drug = Drug.create! valid_attributes
        patch drug_url(drug), params: { drug: new_attributes }
        drug.reload
        expect(response).to redirect_to(drug_url(drug))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        drug = Drug.create! valid_attributes
        patch drug_url(drug), params: { drug: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested drug" do
      drug = Drug.create! valid_attributes
      expect {
        delete drug_url(drug)
      }.to change(Drug, :count).by(-1)
    end

    it "redirects to the drugs list" do
      drug = Drug.create! valid_attributes
      delete drug_url(drug)
      expect(response).to redirect_to(drugs_url)
    end
  end
end
